openapi: 3.0.0 info:
  title: Sichain API
  version: 0.0.4
servers:
# Added by API Auto Mocking Plugin
- url: https://i7q5doxsoi.execute-api.us-east-2.amazonaws.com/beta
  description: AWS API Gateway
tags:
- name: Pools
  description: Contains all endpoints for pool details
- name: Validators
  description: Contains all endpoints for Validators
- name: Peggy
  description: Cointains all endpoints for Peggy
- name: Assets
  description: Contains all endpoints for Assets
- name: Network
  description: Contains all endpoints for Network Info
paths:
  /pool:
    get:
      tags:
      - Pools
      operationId: getPools
      responses:
        "200":
          description: This endpoint gets all available Pools information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/getPoolsResponse'
      x-swagger-router-controller: Pools
  /pool/{symbol}:
    get:
      tags:
      - Pools
      operationId: getPool
      parameters:
      - name: symbol
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Display individual Pool info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getPoolResponse'
      x-swagger-router-controller: Pools                
  /pool/{symbol}/liquidityProvider:
    get:
      tags:
      - Pools
      operationId: getLiquidityProviders
      parameters:
      - name: symbol
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Displays all current Liquidity Providers for the specified
            Pool
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/getLiquidityProvidersResponse'
      x-swagger-router-controller: Pools  
  /pool/{symbol}/liquidityProvider/{lpAddress}:
    get:
      tags:
      - Pools
      operationId: getLiquidityProvider
      parameters:
      - name: symbol
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: lpAddress
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Displays single Liquidity Provider information for the specified
            Pool
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getLiquidityProviderResponse'
      x-swagger-router-controller: Pools                  
  /pool/{symbol}/liquidityProvider/{lpAddress}/share:
    get:
      tags:
      - Pools
      operationId: getPoolShare
      parameters:
      - name: symbol
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: lpAddress
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: This endpoint gets pool share for given Liquidity Provider
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoolShareResponse'
      x-swagger-router-controller: Pools                  
  /validator:
    get:
      tags:
      - Validators
      operationId: getValidators
      responses:
        "200":
          description: This endpoint gets information for all Validators.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetValidatorsResponse'
      x-swagger-router-controller: Validators                
  /validator/{validatorAddress}:
    get:
      tags:
      - Validators
      operationId: getValidator
      parameters:
      - name: validatorAddress
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: This endpoint gets Validator information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetValidatorResponse'
      x-swagger-router-controller: Validators                 
  /validator/{validatorAddress}/delegator:
    get:
      tags:
      - Validators
      operationId: getDelegators
      parameters:
      - name: validatorAddress
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: This endpoint gets Validator Delegator information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDelegatorsResponse'
      x-swagger-router-controller: Validators                  
  /validator/delegator/{delegatorAddress}:
    get:
      tags:
      - Validators
      operationId: getDelegator
      parameters:
      - name: delegatorAddress
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: This endpoint gets specific Delegator information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDelegatorResponse'
      x-swagger-router-controller: Validators                  
  /validator/inactiveValidators:
    get:
      tags:
      - Validators
      operationId: getInactiveValidators
      responses:
        "200":
          description: This end point gets all inactive validators
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/getInactiveValidatorsResponse'
      x-swagger-router-controller: Validators                    
  /validator/delegator/totalStaked:
    get:
      tags:
      - Validators
      operationId: getTotalStakedByDelegators
      responses:
        "200":
          description: This end point gets total token amount delegated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTotalStakedByDelegatorsResponse'
      x-swagger-router-controller: Validators                  
  /peggy/peggedAssets:
    get:
      tags:
      - Peggy
      operationId: getPeggedAssets
      parameters:
      - name: key
        in: query
        required: true
        style: form
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: This endpoint gets pegged assets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/getPeggedAssetsResponse'
      x-swagger-router-controller: Peggy                  
  /asset/{symbol}:
    get:
      tags:
      - Assets
      operationId: getTokenValue
      parameters:
      - name: symbol
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: This endpoint gets USD value of token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTokenValueResponse'
      x-swagger-router-controller: Assets
  /asset/totalSupply:
    get:
      tags:
      - Assets
      operationId: getTotalSupply
      responses:
        "200":
          description: This end point gets total supply of Rowan.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCirculatingSupplyResponse'
      x-swagger-router-controller: Assets
      
  /network:
    get:
      tags:
      - Network
      operationId: getNetworkInfo
      responses:
        "200":
          description: This end point gets network information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/networkResponse'
      x-swagger-router-controller: Network
    
  /dailyPrice:
    get:
      tags:
      - Network
      operationId: getDailyPrice
      responses:
        "200":
          description: This end point gets daily OHLC ticker data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/networkResponse'
      x-swagger-router-controller: Network
      
  /historicalPrice/{symbol}:
    get:
      tags:
      - Network
      operationId: getHistoricalPrice
      parameters:
      - name: symbol
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: This end point gets daily OHLC ticker data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/networkResponse'
      x-swagger-router-controller: Network
  
components:
  schemas:
    getPoolsResponse:
      type: object
      properties:
        externalAsset:
          $ref: '#/components/schemas/externalAsset'
        nativeAsset:
          $ref: '#/components/schemas/nativeAsset'
        poolUnits:
          type: string
          example: '123456'
    getPoolResponse:
      type: object
      properties:
        Pool:
          $ref: '#/components/schemas/getPoolsResponse'
        clpModuleAddress:
          type: string
        height:
          type: string
    getLiquidityProvidersResponse:
      type: object
      properties:
        units:
          type: string
        address:
          type: string
      example:
        units: '123456'
        address: 'jk32l4j3l4j3l2j4l324jlhggfv3'
    getLiquidityProviderResponse:
      type: object
      properties:
        LiquidityProvider:
          $ref: '#/components/schemas/getLiquidityProvidersResponse'
        externalAsset:
          $ref: '#/components/schemas/externalAsset'
        nativeAsset:
          $ref: '#/components/schemas/nativeAsset'
        height:
          type: string
    PoolShareResponse:
      type: object
      properties:
        poolShare:
          type: string
      example:
        poolShare: '0.800828190461011502065957'
    GetValidatorsResponse:
      type: array
      items:
        type: object
      properties:
        validatorAddress:
          type: string
        commissionRate:
          type: string
      example:
        commissionRate: '0.80082819046101150206595775671303272247314453125'
        validatorAddress: sifj890868767868969837739example
    GetValidatorResponse:
      type: object
      properties:
        validatorAddress:
          type: string
        name:
          type: string
        stakedAmount:
          type: string
        selfDelegation:
          type: string
        externalDelegation:
          type: string
        unclaimedRewards:
          type: string
        isSlashed:
          type: boolean
        balance:
          type: string
        performance:
          type: string
          description: Validator uptime percentage over last 30 days
      example:
        stakedAmount: '0.80082819046101150206595775671303272247314453125'
        performance: '2.3021358869347654518833223846741020679473876953125'
        isSlashed: true
        balance: '5.63737665663332876420099637471139430999755859375'
        validatorAddress: validatorAddress
        name: name
        externalDelegation: '1.46581298050294517310021547018550336360931396484375'
        unclaimedRewards: '5.962133916683182377482808078639209270477294921875'
        selfDelegation: '6.02745618307040320615897144307382404804229736328125'
    GetDelegatorsResponse:
      type: array
      items:
        type: object
        properties:
          delegatorAddress:
            type: string
          delegationTotal:
            type: string
        example:
          delegatorAddress: sifj890868767868969837739example
          delegationTotal: '0.80082819046101150206595775671303272247314453125'
    GetDelegatorResponse:
      type: object
      properties:
        validatorAddress:
          type: string
        validatorName:
          type: string
        delegationTotal:
          type: string
        unclaimedRewards:
          type: string
        isSlashed:
          type: boolean
        performance:
          type: string
          description: Validator uptime percentage over last 30 days
      example:
        performance: '1.46581298050294517310021547018550336360931396484375'
        isSlashed: true
        validatorAddress: sifj890868767868969837739example
        validatorName: validatorName
        delegationTotal: '0.80082819046101150206595775671303272247314453125'
        unclaimedRewards: '6.02745618307040320615897144307382404804229736328125'
    GetTokenValueResponse:
      type: object
      properties:
        symbol:
          type: string
        priceInUSDC:
          type: string
        priceInRowan:
          type: string
      example:
        symbol: symbol
        priceInUSDC: '0.80082819046101150206595775671303272247314453125'
        priceInRowan: '6.02745618307040320615897144307382404804229736328125'
    getInactiveValidatorsResponse:
      type: object
      properties:
        inactiveValidator:
          type: string
          example: "abcuiyi88y, yuy7112zy"
      example:
        inactiveValidator: inactiveValidator
    getTotalStakedByDelegatorsResponse:
      type: object
      properties:
        amountDelegated:
          type: string
      example:
        amountDelegated: '0.80082819046101150206595775671303272247314453125'
    getPeggedAssetsResponse:
      type: object
      properties:
        tokenName:
          type: string
          example: cUSD
        value:
          type: string
          example: '120.5'
    getCirculatingSupplyResponse:
      type: object
      properties:
        circulatingSupply:
          type: string
          example: '120'
    networkResponse:
      type: object
      properties:
        totalRowanStaked:
          type: string
          example: '120'
        totalUSDStaked:
          type: string
          example: '120'
        blockReward:
          type: string
          example: '120'
        averageBlockTime:
          type: string
          example: '120'
        averageFee:
          type: string
          example: '120'
        totalUsers:
          type: string
          example: "abcuiyi88y, yuy7112zy"
        networkBondingTime:
          type: string
          example: '245'
        validatorMinimumBondAmount:
          type: string
          example: '10'
        delegatorMinimumBondAmount:
          type: string
          example: '10'
    externalAsset:
      type: object
      properties:
        symbol:
          type: string
        balance:
          type: string
      example:
        symbol: USDC
        balance: '12345556'
    nativeAsset:
      type: object
      properties:
        symbol:
          type: string
          default: ROWAN
        balance:
          type: string
      example:
        symbol: ROWAN
        balance: '12345556'
x-aws-api-id: 'i7q5doxsoi'
